openapi: 3.0.0
info:
  title: 'Mon api blog'
  description: 'Une api pour récupérer tous mes articles de blog'
  version: '0.1'
servers:
  -
    url: 'localhost:8888/apirest'
    description: 'Racine d''url de l''api'
paths:
  /categorie:
    get:
      parameters:
        -
          name: limit
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 'Récupération des catégories'
          content:
            application/json:
              schema:
                description: ''
                type: array
                items:
                  $ref: '#/components/schemas/Categorie'
  '/categorie/{id}':
    get:
      parameters:
        -
          name: id
          in: path
          description: 'Id de la catégorie dont on souhaite récupérer les informations'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Récupération d''une catégorie en fonction de l''id'
          content:
            application/json:
              schema:
                description: ''
                type: array
                items:
                  $ref: '#/components/schemas/Categorie'
components:
  schemas:
    Categorie:
      properties:
        id:
          type: integer
        name:
          type: string
        createdAt:
          type: string
          format: date-time
          nullable: true
      type: object
